[package]
name = "matchbook-util"
version = "0.1.0"
authors = ["Will Johnston <wbjohnston@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matchbook-types = { path = "../matchbook-types" }
socket2 = { version = "0.3.4", features = ["reuseport"] }
bytes = "1"
tokio-util = {version = "0.6.4", features = ["codec", "net"]}
serde_json = "1.0"
fixer-upper = { path = "../fixer-upper"}
futures = "0.3.13"
tokio = {version = "1.18.5", features = ["net"]}
