name: validate-all-projects
# on:
#     push:
#         branches:
#             - main
#     pull_request:
#         branches:
#             - main

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                project-dir: [
                    ./services/matching-engine,
                    ./services/port,
                    ./services/retransmitter,
                    ./packages/matchbook-util,
                    ./packages/matchbook-types,
                    ./packages/fixer-upper
                ]
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: 1.50.0
                default: true
                override: true
            - uses: actions/cache@v2
              working-directory: ${{ matrix.project-dir }}
              with:
                path: |
                    ~/cargo/registry/index
                    ~/.cargo/registry/cache
                    ~/.cargo/registry/git
                    ./target
                    !./target/build/matching-engine*
                    !./target/deps/matching-engine*
                    !./target/build/port*
                    !./target/deps/port*
                    !./target/build/retransmitter*
                    !./target/deps/retransmitter*
                    !./target/build/matchbook-types*
                    !./target/deps/matchbook-types*
                    !./target/build/matchbook-util*
                    !./target/deps/matchbook-util*
                    !./target/build/fixer-upper*
                    !./target/deps/fixer-upper*
                  key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
            - name: build
              run: cargo build
              working-directory: ${{ matrix.project-dir }}
    lint:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                project-dir: [
                    ./services/matching-engine,
                    ./services/port,
                    ./services/retransmitter,
                    ./packages/matchbook-util,
                    ./packages/matchbook-types,
                    ./packages/fixer-upper
                ]
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: 1.50.0
                default: true
                override: true
                components: rustfmt, clippy
            - uses: actions/cache@v2
              working-directory: ${{ matrix.project-dir }}
              with:
                path: |
                    ~/cargo/registry/index
                    ~/.cargo/registry/cache
                    ~/.cargo/registry/git
                    ./target
                    !./target/build/matching-engine*
                    !./target/deps/matching-engine*
                    !./target/build/port*
                    !./target/deps/port*
                    !./target/build/retransmitter*
                    !./target/deps/retransmitter*
                    !./target/build/matchbook-types*
                    !./target/deps/matchbook-types*
                    !./target/build/matchbook-util*
                    !./target/deps/matchbook-util*
                    !./target/build/fixer-upper*
                    !./target/deps/fixer-upper*
            - name: lint
              working-directory: ${{ matrix.project-dir }}
              run: cargo clippy --all-targets --all-features -- -D warnings
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                project-dir: [
                    ./services/matching-engine,
                    ./services/port,
                    ./services/retransmitter,
                    ./packages/matchbook-util,
                    ./packages/matchbook-types,
                    ./packages/fixer-upper
                ]
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: 1.50.0
                default: true
                override: true
            - uses: actions/cache@v2
              working-directory: ${{ matrix.project-dir }}
              with:
                path: |
                    ~/cargo/registry/index
                    ~/.cargo/registry/cache
                    ~/.cargo/registry/git
                    ./target
                    !./target/build/matching-engine*
                    !./target/deps/matching-engine*
                    !./target/build/port*
                    !./target/deps/port*
                    !./target/build/retransmitter*
                    !./target/deps/retransmitter*
                    !./target/build/matchbook-types*
                    !./target/deps/matchbook-types*
                    !./target/build/matchbook-util*
                    !./target/deps/matchbook-util*
                    !./target/build/fixer-upper*
                    !./target/deps/fixer-upper*
            - name: test
              run: cargo test
              working-directory: ${{ matrix.project-dir }}
