name: validate-all-projects
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main


jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                project-dir: [
                    ./services/matching-engine,
                    ./services/port,
                    ./services/retransmitter,
                    ./packages/matchbook-util,
                    ./packages/matchbook-types,
                    ./packages/fixer-upper
                ]
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: 1.50.0
                default: true
                override: true
            - uses: Swatinem/rust-cache@v1
              with:
                working-directory: ${{matrix.project-dir}}
            - name: build
              run: cargo build
              working-directory: ${{ matrix.project-dir }}
    lint:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                project-dir: [
                    ./services/matching-engine,
                    ./services/port,
                    ./services/retransmitter,
                    ./packages/matchbook-util,
                    ./packages/matchbook-types,
                    ./packages/fixer-upper
                ]
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: 1.50.0
                default: true
                override: true
                components: rustfmt, clippy
            - uses: Swatinem/rust-cache@v1
              with:
                working-directory: ${{matrix.project-dir}}
            - name: lint
              working-directory: ${{ matrix.project-dir }}
              run: cargo clippy --all-targets --all-features -- -D warnings
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                project-dir: [
                    ./services/matching-engine,
                    ./services/port,
                    ./services/retransmitter,
                    ./packages/matchbook-util,
                    ./packages/matchbook-types,
                    ./packages/fixer-upper
                ]
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: 1.50.0
                default: true
                override: true
            - uses: Swatinem/rust-cache@v1
              with:
                working-directory: ${{matrix.project-dir}}
            - name: test
              run: cargo test
              working-directory: ${{ matrix.project-dir }}
